### PR TITLE
Move `get_the_icon()` and `the_icon()`

### PR DESCRIPTION
**Pull request by MaximeCulea**
Theses functions are more likely helpers functions which could be called as static ones.

### CODE REVIEW

**Comment by MaximeCulea** [comment]
Create a helper class (not service) to use svg service : https://bitbucket.org/beapi/drome-laboratoire-site/src/65f630a8740f2cb80ac4415fc591b08f77552b61/content/themes/drome-laboratoire/functions.php#lines-48

**Comment by romain-d** [comment]
Cool 👍 👍

**Comment by MaximeCulea** [comment]
Are we good here ?

**Comment by romain-d** [comment]
It's good for me ! 👍

**Comment by Cocola** [comment]
@Rahe ok ?

**Comment by Rahe** [comment]
ok

**Pull request merged**
