### PR TITLE
Feature/no favicon

### PR DESCRIPTION
**Pull request by Cocola**
By removing custom favicons and app icons, we drop 200mb from our node_modules folder 🥳
I delete the PHP services and test native WordPress support through the customizer, it work.
I just want you to check if it's ok for you.

NB: if a client want different design from favicon.ico in browser to an apple-touch-icon in iOS, i suggest to add second field dedicated to, in the customizer or theme option.

### CODE REVIEW

**Comment by asadowski10** [comment]
@Cocola We disable customization on our projects to prevent customers from having additional options not used.

**Comment by Cocola** [comment]
@asadowski10 It will be used because favicon are no longer provided by BFF so we need a solution:

- keep customizer
- provide an equivalent solution in ACF theme option

We can slack on it if you want :)

**Comment by Rahe** [comment]
This could be a great idea to move this kind of settings to the customizer, allowing SVGs to be uploaded.
We can selectively add/remove parts of the customizer and leave only the basics, removing the logo or this kind of stuff.

**Comment by Cocola** [comment]
@Rahe @asadowski10 Up, how can we handle favicons without customizer ?

**Comment by Cocola** [comment]
@Rahe @asadowski10 great no ? https://github.com/xwp/pwa-wp

**Comment by Cocola** [comment]
@Rahe @herewithme @asadowski10  any news ?

**Comment by herewithme** [comment]
pwa-wp c'est trop fat par rapport à notre besoin.

**Comment by herewithme** [comment]
@firestar300 on peut le virer au profit de la gestion native des favicons de WP.

**Comment by asadowski10** [comment]
Prévoir une discussion en réunion DEV pour cibler les impacts avant de le virer ;) 
Exemple : ne plus mettre le plugin pour supprimer le customizer, prévenir la GDP que c'est à eux de contribuer sur les 200000 sites d'une usine à site etc ;) ça se prépare quoi :D

**Comment by herewithme** [comment]
C'est pas bloquant, go merge.

**Comment by asadowski10** [comment]
ok le chef parle ;)
Faisons

**Pull request merged**
